### ISSUE TITLE
Получение текущего статуса пермишена

### ISSUE THREAD

**Issue by lolketch** [mintrocket/MintPermissions#27]
Привет! После успешного предоставления пермишена посредством `permissionsController.request()`, если запросить текущее состояние через `permissionsController.get()`, последний возвращает старое значение.
Демка: https://github.com/lolketch/DemoMintPermissions

**Comment by RadiationX** [comment]
Неловко получилось. Как раз в последнем релизе это исправлял.
Разбираюсь в чем дело

**Comment by RadiationX** [comment]
Исправил, проверил на вашем примере - теперь работает.
Обновите версию до 1.1.1 и проверьте ок/неок

**Comment by lolketch** [comment]
Всё работает) Спасибо!
